BEGIN TOOL.T MM Version: 'Update:110.24'
T       NAME                            L           R           R2          DL        DR        DR2       TL RT      TIME1 TIME2 CUR_TIME TYP      DOC                             PLC       LCUTS       ANGLE   CUT  LTOL   RTOL   R2TOL  DIRECT  R-OFFS      L-OFFS      LBREAK RBREAK NMAX      LIFTOFF TP_NO  T-ANGLE PITCH   AFC       AFC-LOAD AFC-OVLD1 AFC-OVLD2 LAST_USE            PTYP ACC KINEMATIC           DR2TABLE        OVRTIME 
0       NULLWERKZEUG                    +0          +0          +0          +0        +0        +0        0          0     0     0        9                                        %00000000 +0          +0      0    0      0      0      +0                  0           0      0                0              +0      +0                                                                 0    0                                               
1       MILL_D2_ROUGH                   +30         +1          +0          +0        +0        +0        0          0     0     0        9                                        %00000000 +20         +6      2    0      0      0      -1                  +0          0      0                1              +0      +0                                                                 0    0                                               
57                                      +0          +0          +0          +0        +0        +0        0          0     0     0        99                                       %00000000 +0          +0      0    0      0      0      -1                  +0          0      0                1              +0      +0                                                                 0    0                                               
58                                      +0          +0          +0          +0        +0        +0        0          0     0     0        99                                       %00000000 +0          +0      0    0      0      0      -1                  +0          0      0                1              +0      +0                                                                 0    0                                               
87      TORUS_MILL_D2_05                +60         +1          +0.5        +0        +0        +0        0          0     0     0        0                                        %00000000 +40         +6      2    0      0      0      -1                  +0          0      0                1              +0      +0                                                                 0    0                                               
88      TORUS_MILL_D3_05                +60         +1.5        +0.5        +0        +0        +0        0          0     0     0        0                                        %00000000 +40         +6      2    0      0      0      -1                  +0          0      0                1              +0      +0                                                                 0    0                                               
500     TOUCH_PROBE                     +200        +2          +0          +0        +0        +0        0          0     0     0        21                                       %00000000 +0          +0      0    0      0      0      -1                  +0          0      0                1       1      +0      +0                                                                 0    0   ts_444_s69.cfg                              
[END]
