#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import logging
import time
import pyLSV2
from pyLSV2.const import MemoryType, ChannelSignal
import struct

logging.basicConfig(level=logging.INFO)

with pyLSV2.LSV2("192.168.56.103", port=19000, timeout=5, safe_mode=False) as con:
    availible_signals = con.tst_read_scope_channels()
    # build list with selected signals
    selected_signals = list()
    selected_signals.append(availible_signals[ChannelSignal.s_actual_X])
    selected_signals.append(availible_signals[ChannelSignal.s_actual_Y])
    selected_signals.append(availible_signals[ChannelSignal.s_actual_Z])
    selected_signals.append(availible_signals[ChannelSignal.v_actual_X])
    selected_signals.append(availible_signals[ChannelSignal.a_actual_X])
    print("selected signals:")
    for sig in selected_signals:
        print("# %s" % sig)
    # take readings
    readings = con.real_time_readings(
        signal_list=selected_signals, num_readings= 100 , intervall_us=3000
    )
