# This workflow enforces code style with black on each push and pull request
# https://black.readthedocs.io/en/stable/integrations/github_actions.html

name: Lint with Black

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: psf/black@stable
  